sudo: required

language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgtk2.0-dev libjack-jackd2-dev libasound-dev liblash-compat-dev dssi-dev liblo-dev libsndfile-dev liboscpack-dev autopoint intltool pandoc
  - pip install --user cpp-coveralls

script:
  - ./autogen.sh
  - ./configure
  - make V=1 distcheck
  - make clean
  - ./configure --without-alsa
  - make V=1 check
  - make clean
  - ./configure --without-jack
  - make V=1 check
  - make clean
  - ./configure --without-gui
  - make V=1 check
  - make clean
  - ./configure --without-gui --without-alsa --without-jack --without-dssi --without-lv2 --without-vst --prefix=$HOME/.local CFLAGS='-O0 -g -fprofile-arcs -ftest-coverage'
  - make V=1 check

after_success:
  - coveralls --gcov-options '\-lp' -e src/drivers -e src/GUI
